version: '3.8'
services:
  db:
    image: mysql:8
    container_name: slt-mysql
    environment:
      MYSQL_DATABASE: expense_tracker
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: slt-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/expense_tracker?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: slt-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
